AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-app - Compliance Followed Demo

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128

Resources:
  SecureLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.secureHandler
      Environment:
        Variables:
          BUCKET_NAME: !Ref SecureBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /secure
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        TreeShaking: true
        External:
          - aws-sdk
        Bundle: true
        Format: cjs
        EntryPoints:
          - app.ts

  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secure-bucket-3f00289d115df58802100220d0ffc351
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true